### ISSUE TITLE
Would it be possible to allow this mod to be downloaded via the API from curseforge please?

### ISSUE THREAD

**Issue by ilude** [shutdoor/affinity_enchant-forge#1]
Its used in the Mechanical Mastery modpack that Direwolf20 is playing and your mod cannot be downloaded automatically so users must download it manually for running in Itzg's minecraft docker image which for some users adds an extra level of complexity that doesn't seem necessary.

Thanks.

**Comment by shutdoor** [comment]
I've set this mod to allow for use outside of the Curseforge Eco-System. I'm sorry for the delayed response.
